### ISSUE TITLE
Incompatibility with Sound of Token module

### ISSUE THREAD

**Issue by serbandr** [caewok/fvtt-light-mask#16]
FoundryVTT 11.315
PF2e 5.11.5
Light/Sound Mask 0.7.2
[Sound of Token](https://github.com/Aedif/token-sounds) 1.2.0

After testing with Find the Culprit, it seems Light/Sound Mask doesn't play nice with Sound of Token. When trying to create personal Ambient Sounds through the Sound of Token menu on a token, nothing happens and an error is thrown in the console:

TypeError: An error occurred while rendering AmbientSoundCustomConfig 214. Cannot read properties of null (reading 'clone')
    at AmbientSoundCustomConfig._renderAmbientSoundConfig (sound_config.js:32:42)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁AmbientSoundConfig.prototype._render#0 (libWrapper-wrapper.js:189:20)
    at AmbientSoundCustomConfig.render (foundry.js:5769:10)
    at AmbientSoundCustomConfig.render (foundry.js:7111:18)
    at _onAddSoundClick (tokenHooks.js:201:54)
    at HTMLDivElement.<anonymous> (tokenHooks.js:147:29)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

This only happens when both modules are active - if Light/Sound Mask is turned off then there are no issues. Thought to let you know since there aren't any listed conflicts yet on this module's page.

**Comment by pumpkin1972** [comment]
experienced this with dnd 5e too. Raised with sound of token developer, but they highlighted this will also cause issues with modules like mass edit, which also don't assume there will be an ambient sound on the canvas (whereas light/sound mask does, I think)

**Comment by caewok** [comment]
I think I resolved this in v0.7.4.
